# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-26 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prize', '0003_auto_20191026_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Project_image',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
    ]
